[package]
authors = ["IsaMorphic <me@isamorphic.dev>"]
build = "build.rs"
name = "quiche-csbindgen"
version = "0.22.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "*"
csbindgen = "*"